# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: 
      name: staging
      # url: https://staging.myapp.com  # This adds a "View Deployment" button in the UI
    steps:
      - name: Deploy to Staging
        run: echo "deploying to staging"
        env:
          DB_PASS: ${{ secrets.DB_PASSWORD }} # Pulls Staging password

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging             # Wait for staging to succeed
    environment: 
      name: production
      # url: https://myapp.com
    steps:
      - name: Deploy to Production
        run:  echo "deploying to staging"
        env:
          DB_PASS: ${{ secrets.DB_PASSWORD }} # Pulls Prod password automatically
